#https://source.developers.google.com/p/gcp-devops-338510/r/repo-5

steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['clone', 'https://source.developers.google.com/p/gcp-devops-338510/r/repo-5']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t',  'asia.gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia.gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

# kubectl set image deployment/cicd-app-1 runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/kubectl'
  args :
  - 'set'
  - 'image'
  - 'deployment/cicd-app-1'
  - 'image1-sha256-1=asia.gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'
  - 'CLOUDSDK_COMPUTE_REGION=asia-south2'

substitutions:
  _PROJECT_ID : gcpdevops-ocean-434308-j4
  _CINAME : image1
  _VERSION : v4.0

options:
  logging : CLOUD_LOGGING_ONLY
